import { Fighter, CheckIn, HydrationLog, TrainingSession, WeightCutDataPoint, CutProtocolDay } from '../types/camp';

export const INITIAL_FIGHTERS: Fighter[] = [
  {
    id: 'f1',
    name: 'Alex Silva',
    nickname: 'Poatan',
    avatarUrl: 'https://images.unsplash.com/photo-1549476464-37392f717541?w=400&auto=format&fit=crop&q=80',
    pin: '1234',
    weightClass: 'Light Heavyweight',
    divisionLimitLbs: 205.0,
    championshipWeight: true,
    walkoutWeightLbs: 228.0,
    currentWeightLbs: 216.4,
    fightDate: '2026-09-12',
    opponent: 'Magomed Ankalaev',
    event: 'UFC 314 • Main Event',
    record: '12-2-0 (9 KOs)',
    campWeeksTotal: 10,
    campWeekCurrent: 9,
    status: 'optimal',
    statusMessage: 'On target for safe water cut phase in 3 days',
  },
  {
    id: 'f2',
    name: 'Sean Martinez',
    nickname: 'Sugar',
    avatarUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400&auto=format&fit=crop&q=80',
    pin: '2222',
    weightClass: 'Bantamweight',
    divisionLimitLbs: 135.0,
    championshipWeight: false,
    walkoutWeightLbs: 153.0,
    currentWeightLbs: 142.8,
    fightDate: '2026-09-19',
    opponent: 'Merab Dvalishvili',
    event: 'UFC 314 • Co-Main',
    record: '18-2-0 (12 KOs)',
    campWeeksTotal: 12,
    campWeekCurrent: 10,
    status: 'optimal',
    statusMessage: 'Striking volume peaking this week, weight curve ahead of pace',
  },
  {
    id: 'f3',
    name: 'Valentina Santos',
    nickname: 'Bullet',
    avatarUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&auto=format&fit=crop&q=80',
    pin: '3333',
    weightClass: 'Flyweight',
    divisionLimitLbs: 125.0,
    championshipWeight: true,
    walkoutWeightLbs: 139.0,
    currentWeightLbs: 129.8,
    fightDate: '2026-09-08',
    opponent: 'Alexa Grasso',
    event: 'UFC 314 • Main Card',
    record: '24-3-0 (8 KOs)',
    campWeeksTotal: 8,
    campWeekCurrent: 8,
    status: 'warning',
    statusMessage: 'Water flush begins today; monitor sodium & urine scale',
  },
  {
    id: 'f4',
    name: 'Justin Vance',
    nickname: 'The Brawler',
    avatarUrl: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=400&auto=format&fit=crop&q=80',
    pin: '4444',
    weightClass: 'Lightweight',
    divisionLimitLbs: 155.0,
    championshipWeight: false,
    walkoutWeightLbs: 174.0,
    currentWeightLbs: 167.2,
    fightDate: '2026-09-26',
    opponent: 'Dustin Poirier',
    event: 'Fight Night 188 • Main Event',
    record: '25-5-0 (20 KOs)',
    campWeeksTotal: 10,
    campWeekCurrent: 7,
    status: 'critical',
    statusMessage: 'Right shin contusion & elevated RPE (8.5/10) reported in sparring',
  },
];

export const INITIAL_CHECKINS: CheckIn[] = [
  {
    id: 'c1',
    fighterId: 'f1',
    timestamp: '2026-09-03T07:15:00Z',
    date: '2026-09-03',
    weightLbs: 216.4,
    sleepHours: 8.2,
    sleepQuality: 4,
    sorenessLevel: 3,
    sorenessAreas: ['neck', 'shins'],
    restingHR: 48,
    mentalFocus: 5,
    rpeFatigue: 4,
    notes: 'Feeling sharp. Left hand wrap felt comfortable during bag work.',
    synced: true,
  },
  {
    id: 'c2',
    fighterId: 'f2',
    timestamp: '2026-09-03T08:00:00Z',
    date: '2026-09-03',
    weightLbs: 142.8,
    sleepHours: 7.5,
    sleepQuality: 5,
    sorenessLevel: 2,
    sorenessAreas: ['shoulders'],
    restingHR: 52,
    mentalFocus: 5,
    rpeFatigue: 3,
    notes: 'Weight dropping smooth, energy high for 5 hard rounds today.',
    synced: true,
  },
  {
    id: 'c3',
    fighterId: 'f3',
    timestamp: '2026-09-03T06:45:00Z',
    date: '2026-09-03',
    weightLbs: 129.8,
    sleepHours: 6.8,
    sleepQuality: 3,
    sorenessLevel: 4,
    sorenessAreas: ['lowerBack', 'hips'],
    restingHR: 56,
    mentalFocus: 4,
    rpeFatigue: 6,
    notes: 'Hunger kicking in with calorie taper. Sweating well in morning shadowboxing.',
    synced: true,
  },
  {
    id: 'c4',
    fighterId: 'f4',
    timestamp: '2026-09-03T09:10:00Z',
    date: '2026-09-03',
    weightLbs: 167.2,
    sleepHours: 5.5,
    sleepQuality: 2,
    sorenessLevel: 8,
    sorenessAreas: ['shins', 'ribs', 'hands'],
    restingHR: 64,
    mentalFocus: 3,
    rpeFatigue: 8,
    notes: 'Right shin bruised after blocking head kick yesterday. Needs ice & ultrasound.',
    synced: true,
  },
];

export const INITIAL_HYDRATION: HydrationLog[] = [
  {
    id: 'h1',
    fighterId: 'f1',
    date: '2026-09-03',
    waterIntakeOz: 160,
    targetWaterOz: 192, // 1.5 Gallons
    electrolytesPackets: 2,
    urineColorScale: 2,
    lastUpdated: '2026-09-03T14:30:00Z',
    synced: true,
  },
  {
    id: 'h2',
    fighterId: 'f2',
    date: '2026-09-03',
    waterIntakeOz: 128,
    targetWaterOz: 160,
    electrolytesPackets: 2,
    urineColorScale: 1,
    lastUpdated: '2026-09-03T13:45:00Z',
    synced: true,
  },
  {
    id: 'h3',
    fighterId: 'f3',
    date: '2026-09-03',
    waterIntakeOz: 210,
    targetWaterOz: 256, // 2 Gallons Water Load phase
    electrolytesPackets: 3,
    urineColorScale: 1,
    lastUpdated: '2026-09-03T15:00:00Z',
    synced: true,
  },
  {
    id: 'h4',
    fighterId: 'f4',
    date: '2026-09-03',
    waterIntakeOz: 80,
    targetWaterOz: 180,
    electrolytesPackets: 1,
    urineColorScale: 4, // Dehydrated warning
    lastUpdated: '2026-09-03T12:00:00Z',
    synced: true,
  },
];

export const INITIAL_TRAINING_SESSIONS: TrainingSession[] = [
  {
    id: 't1',
    fighterId: 'f1',
    date: '2026-09-03',
    time: '10:00 AM',
    title: 'Championship Hard Sparring (5x5)',
    type: 'sparring',
    durationMinutes: 45,
    targetRounds: 5,
    intensity: 'High',
    targetRpe: 8,
    actualRpe: 8,
    coachNotes: 'Rotate fresh partners each round. Focus on calf kick distance and checking incoming single legs.',
    fighterNotes: 'Landed clean hooks in rounds 3 & 4. Defense felt impenetrable.',
    completed: true,
    completedAt: '2026-09-03T11:05:00Z',
    rounds: [
      { roundNumber: 1, durationMinutes: 5, completed: true, notes: 'Striking range feeling, checked 2 kicks' },
      { roundNumber: 2, durationMinutes: 5, completed: true, notes: 'Cage pressure, high volume' },
      { roundNumber: 3, durationMinutes: 5, completed: true, notes: 'Fresh southpaw partner, counter left hook landed' },
      { roundNumber: 4, durationMinutes: 5, completed: true, notes: 'Defended takedown against fence' },
      { roundNumber: 5, durationMinutes: 5, completed: true, notes: 'High pace championship round' },
    ],
  },
  {
    id: 't2',
    fighterId: 'f1',
    date: '2026-09-03',
    time: '04:30 PM',
    title: 'Wall Wrestling & Takedown Defense',
    type: 'wrestling_grappling',
    durationMinutes: 60,
    targetRounds: 4,
    intensity: 'High',
    targetRpe: 7,
    coachNotes: 'Pummeling, underhook escapes, and immediate framing on cage breaks.',
    completed: false,
    rounds: [
      { roundNumber: 1, durationMinutes: 5, completed: false },
      { roundNumber: 2, durationMinutes: 5, completed: false },
      { roundNumber: 3, durationMinutes: 5, completed: false },
      { roundNumber: 4, durationMinutes: 5, completed: false },
    ],
  },
  {
    id: 't3',
    fighterId: 'f1',
    date: '2026-09-03',
    time: '07:30 PM',
    title: 'Contrast Hydrotherapy & Normatec Flush',
    type: 'recovery',
    durationMinutes: 40,
    intensity: 'Low',
    targetRpe: 2,
    coachNotes: '15 min cold plunge (48F) -> 15 min infrared sauna -> 20 min leg compression.',
    completed: false,
  },
  {
    id: 't4',
    fighterId: 'f2',
    date: '2026-09-03',
    time: '09:30 AM',
    title: 'Precision Mitts & Angle Work',
    type: 'striking',
    durationMinutes: 50,
    targetRounds: 6,
    intensity: 'High',
    targetRpe: 7,
    coachNotes: 'Speed bursts, spinning back kicks to liver, stance switches.',
    completed: true,
    completedAt: '2026-09-03T10:30:00Z',
  },
  {
    id: 't5',
    fighterId: 'f3',
    date: '2026-09-03',
    time: '11:00 AM',
    title: 'Sweat Sweat & Clinch Control',
    type: 'wrestling_grappling',
    durationMinutes: 40,
    targetRounds: 3,
    intensity: 'Moderate',
    targetRpe: 6,
    coachNotes: 'Muay Thai clinch knees, keep sweat going for water flush.',
    completed: true,
    completedAt: '2026-09-03T11:50:00Z',
  },
  {
    id: 't6',
    fighterId: 'f4',
    date: '2026-09-03',
    time: '10:00 AM',
    title: 'Dutch Kickboxing Combinations',
    type: 'striking',
    durationMinutes: 60,
    targetRounds: 5,
    intensity: 'High',
    targetRpe: 9,
    coachNotes: 'Low kicks disabled today due to right shin contusion. Hands and body punches only.',
    completed: true,
    completedAt: '2026-09-03T11:15:00Z',
  }
];

export const MOCK_WEIGHT_TRAJECTORY: Record<string, WeightCutDataPoint[]> = {
  f1: [
    { dayNumber: 1, date: 'Aug 21', daysOut: 22, targetWeightLbs: 225.0, actualWeightLbs: 225.4, eveningWeightLbs: 227.1, dangerZoneThresholdLbs: 230.0, isWaterCutPhase: false },
    { dayNumber: 2, date: 'Aug 23', daysOut: 20, targetWeightLbs: 224.0, actualWeightLbs: 223.8, eveningWeightLbs: 225.5, dangerZoneThresholdLbs: 229.0, isWaterCutPhase: false },
    { dayNumber: 3, date: 'Aug 25', daysOut: 18, targetWeightLbs: 223.0, actualWeightLbs: 222.9, eveningWeightLbs: 224.2, dangerZoneThresholdLbs: 228.0, isWaterCutPhase: false },
    { dayNumber: 4, date: 'Aug 27', daysOut: 16, targetWeightLbs: 221.8, actualWeightLbs: 221.2, eveningWeightLbs: 223.0, dangerZoneThresholdLbs: 226.5, isWaterCutPhase: false },
    { dayNumber: 5, date: 'Aug 29', daysOut: 14, targetWeightLbs: 220.5, actualWeightLbs: 220.1, eveningWeightLbs: 221.9, dangerZoneThresholdLbs: 225.0, isWaterCutPhase: false },
    { dayNumber: 6, date: 'Aug 31', daysOut: 12, targetWeightLbs: 219.0, actualWeightLbs: 218.6, eveningWeightLbs: 220.4, dangerZoneThresholdLbs: 223.5, isWaterCutPhase: false },
    { dayNumber: 7, date: 'Sep 02', daysOut: 10, targetWeightLbs: 217.5, actualWeightLbs: 217.2, eveningWeightLbs: 219.0, dangerZoneThresholdLbs: 222.0, isWaterCutPhase: false },
    { dayNumber: 8, date: 'Sep 03', daysOut: 9, targetWeightLbs: 216.5, actualWeightLbs: 216.4, eveningWeightLbs: undefined, dangerZoneThresholdLbs: 221.0, isWaterCutPhase: false, notes: 'Today (Morning Scale)' },
    { dayNumber: 9, date: 'Sep 05', daysOut: 7, targetWeightLbs: 215.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 219.5, isWaterCutPhase: false },
    { dayNumber: 10, date: 'Sep 07', daysOut: 5, targetWeightLbs: 214.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 218.0, isWaterCutPhase: true, notes: 'Water Loading Start (2 Gal/day)' },
    { dayNumber: 11, date: 'Sep 09', daysOut: 3, targetWeightLbs: 212.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 216.0, isWaterCutPhase: true, notes: 'Sodium Cut & Water Taper' },
    { dayNumber: 12, date: 'Sep 11', daysOut: 1, targetWeightLbs: 207.5, actualWeightLbs: undefined, dangerZoneThresholdLbs: 212.0, isWaterCutPhase: true, notes: 'Sauna Sweats (Evening)' },
    { dayNumber: 13, date: 'Sep 12', daysOut: 0, targetWeightLbs: 205.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 209.0, isWaterCutPhase: true, notes: 'OFFICIAL WEIGH-IN (09:00 AM)' },
  ],
  f2: [
    { dayNumber: 1, date: 'Aug 25', daysOut: 25, targetWeightLbs: 151.0, actualWeightLbs: 150.8, dangerZoneThresholdLbs: 154.0, isWaterCutPhase: false },
    { dayNumber: 2, date: 'Aug 29', daysOut: 21, targetWeightLbs: 148.5, actualWeightLbs: 147.9, dangerZoneThresholdLbs: 151.0, isWaterCutPhase: false },
    { dayNumber: 3, date: 'Sep 01', daysOut: 18, targetWeightLbs: 145.5, actualWeightLbs: 144.6, dangerZoneThresholdLbs: 148.0, isWaterCutPhase: false },
    { dayNumber: 4, date: 'Sep 03', daysOut: 16, targetWeightLbs: 143.5, actualWeightLbs: 142.8, dangerZoneThresholdLbs: 146.0, isWaterCutPhase: false },
    { dayNumber: 5, date: 'Sep 08', daysOut: 11, targetWeightLbs: 141.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 143.5, isWaterCutPhase: false },
    { dayNumber: 6, date: 'Sep 14', daysOut: 5, targetWeightLbs: 139.5, actualWeightLbs: undefined, dangerZoneThresholdLbs: 142.0, isWaterCutPhase: true },
    { dayNumber: 7, date: 'Sep 19', daysOut: 0, targetWeightLbs: 135.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 138.0, isWaterCutPhase: true },
  ],
  f3: [
    { dayNumber: 1, date: 'Aug 20', daysOut: 19, targetWeightLbs: 136.0, actualWeightLbs: 136.2, dangerZoneThresholdLbs: 138.5, isWaterCutPhase: false },
    { dayNumber: 2, date: 'Aug 26', daysOut: 13, targetWeightLbs: 134.0, actualWeightLbs: 133.7, dangerZoneThresholdLbs: 136.5, isWaterCutPhase: false },
    { dayNumber: 3, date: 'Aug 31', daysOut: 8, targetWeightLbs: 131.5, actualWeightLbs: 131.1, dangerZoneThresholdLbs: 134.0, isWaterCutPhase: true },
    { dayNumber: 4, date: 'Sep 03', daysOut: 5, targetWeightLbs: 130.0, actualWeightLbs: 129.8, dangerZoneThresholdLbs: 132.5, isWaterCutPhase: true },
    { dayNumber: 5, date: 'Sep 06', daysOut: 2, targetWeightLbs: 128.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 130.0, isWaterCutPhase: true },
    { dayNumber: 6, date: 'Sep 08', daysOut: 0, targetWeightLbs: 125.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 127.5, isWaterCutPhase: true },
  ],
  f4: [
    { dayNumber: 1, date: 'Aug 20', daysOut: 37, targetWeightLbs: 173.0, actualWeightLbs: 173.5, dangerZoneThresholdLbs: 176.0, isWaterCutPhase: false },
    { dayNumber: 2, date: 'Aug 27', daysOut: 30, targetWeightLbs: 170.5, actualWeightLbs: 170.8, dangerZoneThresholdLbs: 174.0, isWaterCutPhase: false },
    { dayNumber: 3, date: 'Sep 03', daysOut: 23, targetWeightLbs: 168.0, actualWeightLbs: 167.2, dangerZoneThresholdLbs: 171.0, isWaterCutPhase: false },
    { dayNumber: 4, date: 'Sep 12', daysOut: 14, targetWeightLbs: 164.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 167.0, isWaterCutPhase: false },
    { dayNumber: 5, date: 'Sep 21', daysOut: 5, targetWeightLbs: 160.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 163.0, isWaterCutPhase: true },
    { dayNumber: 6, date: 'Sep 26', daysOut: 0, targetWeightLbs: 155.0, actualWeightLbs: undefined, dangerZoneThresholdLbs: 158.0, isWaterCutPhase: true },
  ],
};

export const MOCK_CUT_PROTOCOLS: Record<string, CutProtocolDay[]> = {
  f1: [
    {
      daysOut: 5,
      date: 'Sep 07 (Mon)',
      phaseName: 'Hyper-Hydration (Water Loading)',
      waterGoalGal: 2.0,
      sodiumLevel: 'High (Loading)',
      carbsGrams: 200,
      sweatMethod: 'Normal gym floor workout sweat',
      targetWeightLbs: 214.0,
      coachCheckpoints: ['Confirm 2 Gal distilled water intake', 'Salt all meals generously to stimulate aldosterone downregulation', 'Record morning and night weigh-ins'],
    },
    {
      daysOut: 4,
      date: 'Sep 08 (Tue)',
      phaseName: 'High Hydration Maintenance',
      waterGoalGal: 2.0,
      sodiumLevel: 'Normal',
      carbsGrams: 150,
      sweatMethod: 'Drilling with sweat suit (light)',
      targetWeightLbs: 213.5,
      coachCheckpoints: ['Urine color must be transparent (level 1)', 'Monitor resting heart rate & blood pressure', 'Final hard pad work session'],
    },
    {
      daysOut: 3,
      date: 'Sep 09 (Wed)',
      phaseName: 'Sodium Drop & Fluid Taper',
      waterGoalGal: 1.0,
      sodiumLevel: 'Low',
      carbsGrams: 80,
      sweatMethod: 'Shadowboxing & light flow rolling',
      targetWeightLbs: 212.0,
      coachCheckpoints: ['Zero added salt', 'Switch to low-residue foods (white fish, egg whites, asparagus)', 'Aldosterone suppression causes flushing'],
    },
    {
      daysOut: 2,
      date: 'Sep 10 (Thu)',
      phaseName: 'Carb Depletion & Half-Gallon',
      waterGoalGal: 0.5,
      sodiumLevel: 'Zero',
      carbsGrams: 40,
      sweatMethod: 'Hot Epsom Salt Bath (20 min)',
      targetWeightLbs: 210.0,
      coachCheckpoints: ['Strict zero sodium', 'Cut water intake at 6:00 PM', 'Dry sauna protocol ready (towel wraps prepared)'],
    },
    {
      daysOut: 1,
      date: 'Sep 11 (Fri)',
      phaseName: 'Active Sweat & Water Cut',
      waterGoalGal: 0.15, // Ice chips only
      sodiumLevel: 'Zero',
      carbsGrams: 20,
      sweatMethod: 'Sauna: 3 sets x 15 min @ 180°F + cold towel reset',
      targetWeightLbs: 206.5,
      coachCheckpoints: ['Coach monitors pulse every 10 min in sauna', 'Target within 1.5 lbs of official weight before sleeping', 'Sleep in cool dry room'],
    },
    {
      daysOut: 0,
      date: 'Sep 12 (Sat)',
      phaseName: 'Official Weigh-In & Rehydration',
      waterGoalGal: 0.0,
      sodiumLevel: 'Re-hydration',
      carbsGrams: 400,
      sweatMethod: 'None (scale ready at 9:00 AM)',
      targetWeightLbs: 205.0,
      coachCheckpoints: ['Official weight 205.0 lbs locked in', 'Immediate Pedialyte/Gastrolyte oral rehydration: 1L in first 30 min', 'Slow carb loading with sweet potatoes and rice pancakes'],
    },
  ],
};
